### ISSUE TITLE
spawn entities from map configuration

### ISSUE THREAD

**Issue by codingchili** [codingchili/chili-game-ext#73]
sample

Format must be be generatable/parsable from the map designer.
```
- name: "myMapName"
- npcs:
    - name: "..."
- entities: 
    - name: "theConfiguredEntity"
      scale: 2.5
      point:
        x: 500
        y: 500
   ...
```

Note that the map may change over time and we should not be passing the map configuration to the clients.
